#                            _
#  _ __ ___ _ __   ___  __ _| |_ ___ _ __
# | '__/ _ \ '_ \ / _ \/ _` | __/ _ \ '__|
# | | |  __/ |_) |  __/ (_| | ||  __/ |
# |_|  \___| .__/ \___|\__,_|\__\___|_|
#          |_|
#
#  https://github.com/rocats/repeater-v2
#
#  Copyright (C) 2023 @yqlbu
#
#  This is a self-hosted software, licensed under the MIT License.
#  See /License for more information.

name: Build OCI Container (Prod)
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:
  pre-actions:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/pre-actions.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      fetch-depth: 0
      check-runs: '[]'
      notify: false

  build-and-push:
    runs-on: ubuntu-latest
    env:
      dockerfile: Dockerfile
      image_tag: prod-${{ needs.pre-actions.outputs.git_sha_short }}-${{ github.run_number }}
    outputs:
      image_tag: ${{ env.image_tag }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: daeuniverse
          password: ${{ secrets.QUAY_PASS }}
          image: daeuniverse/${{ github.event.repository.name }}
          build_file: ${{ env.dockerfile }}
          tag: ${{ env.image_tag }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/daeuniverse/cache
          extra_args: --build-arg PYTHON_VERSION=3.10

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ github.repository }}:${{ env.image_tag }}"
